#Crie meu container a partir de uma imagem que já possui o Apache instalado, usando Alpine Linux.
FROM httpd:alpine

COPY dist/ /usr/local/apache2/htdocs/
#está copiando a pasta dist do seu computador para dentro do container do Apache.